language: java
jdk:
  - oraclejdk7
  - oraclejdk8

env:
  - CDI=cdi-1.1
  - CDI=cdi-1.2
  - CDI=cdi-2.0
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "MuFf7aXjK4tff5NvKxrm/CH7P95uFjGllPF1kKBtlxit2EO6rf7vwqKkDjAon4sbyYHn1td/TvWb8urUL89sS/Vbc+80GjBvz5UcjZg7P52/g9kHmCtvrxiJuLudCXtFgE31EyQiK4ks6qfvkWSHNNVtobeZMxc+YqsAPfs8bX0="

matrix:
  exclude:
    - jdk: oraclejdk7
      env: CDI=cdi-2.0

script:
  - mvn test -P${CDI}

env:

addons:
  coverity_scan:
    project:
      name: "guhilling/cdi-test"
      description: "Build submitted via Travis CI"
    notification_email: gunnar@hilling.de
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan